# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import service
from google.protobuf import service_reflection
from google.protobuf import descriptor_pb2


_ENVELOPE_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='communication.Envelope.Type',
  filename='Type',
  values=[
    descriptor.EnumValueDescriptor(
      name='CONTROL', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NODE_READINGS', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LINK_READINGS', index=2, number=2,
      options=None,
      type=None),
  ],
  options=None,
)


_CONTROL = descriptor.Descriptor(
  name='Control',
  full_name='communication.Control',
  filename='message.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='destination', full_name='communication.Control.destination', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='capability', full_name='communication.Control.capability', index=1,
      number=2, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lastValue', full_name='communication.Control.lastValue', index=2,
      number=3, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payload', full_name='communication.Control.payload', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_NODEREADINGS_READING = descriptor.Descriptor(
  name='Reading',
  full_name='communication.NodeReadings.Reading',
  filename='message.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='node', full_name='communication.NodeReadings.Reading.node', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='capability', full_name='communication.NodeReadings.Reading.capability', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='communication.NodeReadings.Reading.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stringReading', full_name='communication.NodeReadings.Reading.stringReading', index=3,
      number=4, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='doubleReading', full_name='communication.NodeReadings.Reading.doubleReading', index=4,
      number=5, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_NODEREADINGS = descriptor.Descriptor(
  name='NodeReadings',
  full_name='communication.NodeReadings',
  filename='message.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='reading', full_name='communication.NodeReadings.reading', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_LINKREADINGS_READING = descriptor.Descriptor(
  name='Reading',
  full_name='communication.LinkReadings.Reading',
  filename='message.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='source', full_name='communication.LinkReadings.Reading.source', index=0,
      number=1, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='target', full_name='communication.LinkReadings.Reading.target', index=1,
      number=2, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='capability', full_name='communication.LinkReadings.Reading.capability', index=2,
      number=3, type=9, cpp_type=9, label=2,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='communication.LinkReadings.Reading.timestamp', index=3,
      number=4, type=3, cpp_type=2, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stringReading', full_name='communication.LinkReadings.Reading.stringReading', index=4,
      number=5, type=9, cpp_type=9, label=1,
      default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='doubleReading', full_name='communication.LinkReadings.Reading.doubleReading', index=5,
      number=6, type=1, cpp_type=5, label=1,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)

_LINKREADINGS = descriptor.Descriptor(
  name='LinkReadings',
  full_name='communication.LinkReadings',
  filename='message.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='reading', full_name='communication.LinkReadings.reading', index=0,
      number=1, type=11, cpp_type=10, label=3,
      default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
  ],
  options=None)


_ENVELOPE = descriptor.Descriptor(
  name='Envelope',
  full_name='communication.Envelope',
  filename='message.proto',
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='communication.Envelope.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='control', full_name='communication.Envelope.control', index=1,
      number=2, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nodeReadings', full_name='communication.Envelope.nodeReadings', index=2,
      number=3, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='linkReadings', full_name='communication.Envelope.linkReadings', index=3,
      number=4, type=11, cpp_type=10, label=1,
      default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],  # TODO(robinson): Implement.
  enum_types=[
    _ENVELOPE_TYPE,
  ],
  options=None)


_NODEREADINGS.fields_by_name['reading'].message_type = _NODEREADINGS_READING
_LINKREADINGS.fields_by_name['reading'].message_type = _LINKREADINGS_READING
_ENVELOPE.fields_by_name['type'].enum_type = _ENVELOPE_TYPE
_ENVELOPE.fields_by_name['control'].message_type = _CONTROL
_ENVELOPE.fields_by_name['nodeReadings'].message_type = _NODEREADINGS
_ENVELOPE.fields_by_name['linkReadings'].message_type = _LINKREADINGS

class Control(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROL

class NodeReadings(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Reading(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _NODEREADINGS_READING
  DESCRIPTOR = _NODEREADINGS

class LinkReadings(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Reading(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _LINKREADINGS_READING
  DESCRIPTOR = _LINKREADINGS

class Envelope(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENVELOPE

