# Generated by the protocol buffer compiler.  DO NOT EDIT!

from google.protobuf import descriptor
from google.protobuf import message
from google.protobuf import reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)



DESCRIPTOR = descriptor.FileDescriptor(
  name='message.proto',
  package='communication',
  serialized_pb='\n\rmessage.proto\x12\rcommunication\"V\n\x07\x43ontrol\x12\x13\n\x0b\x64\x65stination\x18\x01 \x02(\t\x12\x12\n\ncapability\x18\x02 \x01(\t\x12\x11\n\tlastValue\x18\x03 \x01(\t\x12\x0f\n\x07payload\x18\x04 \x01(\t\"\xb2\x01\n\x0cNodeReadings\x12\x34\n\x07reading\x18\x01 \x03(\x0b\x32#.communication.NodeReadings.Reading\x1al\n\x07Reading\x12\x0c\n\x04node\x18\x01 \x02(\t\x12\x12\n\ncapability\x18\x02 \x02(\t\x12\x11\n\ttimestamp\x18\x03 \x02(\x03\x12\x15\n\rstringReading\x18\x04 \x01(\t\x12\x15\n\rdoubleReading\x18\x05 \x01(\x01\"\xc4\x01\n\x0cLinkReadings\x12\x34\n\x07reading\x18\x01 \x03(\x0b\x32#.communication.LinkReadings.Reading\x1a~\n\x07Reading\x12\x0e\n\x06source\x18\x01 \x02(\t\x12\x0e\n\x06target\x18\x02 \x02(\t\x12\x12\n\ncapability\x18\x03 \x02(\t\x12\x11\n\ttimestamp\x18\x04 \x02(\x03\x12\x15\n\rstringReading\x18\x05 \x01(\t\x12\x15\n\rdoubleReading\x18\x06 \x01(\x01\"\x89\x02\n\x08\x45nvelope\x12\x33\n\x04type\x18\x01 \x02(\x0e\x32\x1c.communication.Envelope.Type:\x07\x43ONTROL\x12\'\n\x07\x63ontrol\x18\x02 \x01(\x0b\x32\x16.communication.Control\x12\x31\n\x0cnodeReadings\x18\x03 \x01(\x0b\x32\x1b.communication.NodeReadings\x12\x31\n\x0clinkReadings\x18\x04 \x01(\x0b\x32\x1b.communication.LinkReadings\"9\n\x04Type\x12\x0b\n\x07\x43ONTROL\x10\x00\x12\x11\n\rNODE_READINGS\x10\x01\x12\x11\n\rLINK_READINGS\x10\x02\x42-\n\"eu.uberdust.communication.protobufB\x07Message')



_ENVELOPE_TYPE = descriptor.EnumDescriptor(
  name='Type',
  full_name='communication.Envelope.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    descriptor.EnumValueDescriptor(
      name='CONTROL', index=0, number=0,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='NODE_READINGS', index=1, number=1,
      options=None,
      type=None),
    descriptor.EnumValueDescriptor(
      name='LINK_READINGS', index=2, number=2,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=709,
  serialized_end=766,
)


_CONTROL = descriptor.Descriptor(
  name='Control',
  full_name='communication.Control',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='destination', full_name='communication.Control.destination', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='capability', full_name='communication.Control.capability', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='lastValue', full_name='communication.Control.lastValue', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='payload', full_name='communication.Control.payload', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=32,
  serialized_end=118,
)


_NODEREADINGS_READING = descriptor.Descriptor(
  name='Reading',
  full_name='communication.NodeReadings.Reading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='node', full_name='communication.NodeReadings.Reading.node', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='capability', full_name='communication.NodeReadings.Reading.capability', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='communication.NodeReadings.Reading.timestamp', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stringReading', full_name='communication.NodeReadings.Reading.stringReading', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='doubleReading', full_name='communication.NodeReadings.Reading.doubleReading', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=191,
  serialized_end=299,
)

_NODEREADINGS = descriptor.Descriptor(
  name='NodeReadings',
  full_name='communication.NodeReadings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='reading', full_name='communication.NodeReadings.reading', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_NODEREADINGS_READING, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=121,
  serialized_end=299,
)


_LINKREADINGS_READING = descriptor.Descriptor(
  name='Reading',
  full_name='communication.LinkReadings.Reading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='source', full_name='communication.LinkReadings.Reading.source', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='target', full_name='communication.LinkReadings.Reading.target', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='capability', full_name='communication.LinkReadings.Reading.capability', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='timestamp', full_name='communication.LinkReadings.Reading.timestamp', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='stringReading', full_name='communication.LinkReadings.Reading.stringReading', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='doubleReading', full_name='communication.LinkReadings.Reading.doubleReading', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=372,
  serialized_end=498,
)

_LINKREADINGS = descriptor.Descriptor(
  name='LinkReadings',
  full_name='communication.LinkReadings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='reading', full_name='communication.LinkReadings.reading', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_LINKREADINGS_READING, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=302,
  serialized_end=498,
)


_ENVELOPE = descriptor.Descriptor(
  name='Envelope',
  full_name='communication.Envelope',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    descriptor.FieldDescriptor(
      name='type', full_name='communication.Envelope.type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=True, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='control', full_name='communication.Envelope.control', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='nodeReadings', full_name='communication.Envelope.nodeReadings', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    descriptor.FieldDescriptor(
      name='linkReadings', full_name='communication.Envelope.linkReadings', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ENVELOPE_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=501,
  serialized_end=766,
)

_NODEREADINGS_READING.containing_type = _NODEREADINGS;
_NODEREADINGS.fields_by_name['reading'].message_type = _NODEREADINGS_READING
_LINKREADINGS_READING.containing_type = _LINKREADINGS;
_LINKREADINGS.fields_by_name['reading'].message_type = _LINKREADINGS_READING
_ENVELOPE.fields_by_name['type'].enum_type = _ENVELOPE_TYPE
_ENVELOPE.fields_by_name['control'].message_type = _CONTROL
_ENVELOPE.fields_by_name['nodeReadings'].message_type = _NODEREADINGS
_ENVELOPE.fields_by_name['linkReadings'].message_type = _LINKREADINGS
_ENVELOPE_TYPE.containing_type = _ENVELOPE;
DESCRIPTOR.message_types_by_name['Control'] = _CONTROL
DESCRIPTOR.message_types_by_name['NodeReadings'] = _NODEREADINGS
DESCRIPTOR.message_types_by_name['LinkReadings'] = _LINKREADINGS
DESCRIPTOR.message_types_by_name['Envelope'] = _ENVELOPE

class Control(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _CONTROL
  
  # @@protoc_insertion_point(class_scope:communication.Control)

class NodeReadings(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Reading(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _NODEREADINGS_READING
    
    # @@protoc_insertion_point(class_scope:communication.NodeReadings.Reading)
  DESCRIPTOR = _NODEREADINGS
  
  # @@protoc_insertion_point(class_scope:communication.NodeReadings)

class LinkReadings(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  
  class Reading(message.Message):
    __metaclass__ = reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _LINKREADINGS_READING
    
    # @@protoc_insertion_point(class_scope:communication.LinkReadings.Reading)
  DESCRIPTOR = _LINKREADINGS
  
  # @@protoc_insertion_point(class_scope:communication.LinkReadings)

class Envelope(message.Message):
  __metaclass__ = reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _ENVELOPE
  
  # @@protoc_insertion_point(class_scope:communication.Envelope)

# @@protoc_insertion_point(module_scope)
